import { TAGS } from '../../constants/tags';
import type { TestCaseDefinition } from '../../types/test-case.types';

const rankingTags = Object.freeze([TAGS.regression, TAGS.listings]);

export const rankingTestCases: readonly TestCaseDefinition[] = [
  {
    id: 'TC-RANK-ORDER-001',
    title: '[Core Rule 1] Tin VIP Kim Cương đăng lâu (điểm thấp) LUÔN xếp TRÊN tin VIP Vàng vừa đăng (điểm cao)',
    module: 'Ranking',
    priority: 'critical',
    tags: rankingTags,
    preconditions: ['Seed qua API: Tin A = VIP Kim Cương, Cấp 4, đã đăng 168h, Final Score ≈ 0.5; Tin B = VIP Vàng, Cấp 3, vừa đăng 0h, Final Score = 30'],
    testData: 'Từ khóa tìm kiếm chung để 2 tin cùng xuất hiện',
    testSteps: '1. Tìm kiếm/hiển thị danh sách chứa cả 2 tin. 2. Lấy vị trí DOM của các .listing-card.',
    expectedResult: 'Tin A xuất hiện ở vị trí trước Tin B, dù Final Score thấp hơn nhiều — đúng quy tắc Cấp ưu tiên gói xét trước Điểm hiển thị (Mục 6).',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-RANK-ORDER-002',
    title: '[Core Rule 1] Tin VIP Vàng đăng lâu LUÔN xếp TRÊN tin VIP Bạc/Tin Thường mới đăng',
    module: 'Ranking',
    priority: 'critical',
    tags: rankingTags,
    preconditions: ['Seed: Tin A = VIP Vàng, Cấp 3, đăng 72h; Tin B = VIP Bạc, Cấp 2, đăng 2h (khớp ví dụ Mục 7 tài liệu)'],
    testData: 'Danh sách chứa cả 2 tin',
    testSteps: '1. Truy cập danh sách tin đăng. 2. Assert thứ tự DOM Tin A / Tin B.',
    expectedResult: 'Tin A đứng trên Tin B.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-RANK-ORDER-003',
    title: '[Core Rule 2 – Same VIP] Cùng hạng VIP Vàng, tin điểm chất lượng cao hơn xếp TRÊN',
    module: 'Ranking',
    priority: 'high',
    tags: rankingTags,
    preconditions: ['Seed: 2 tin cùng gói VIP Vàng, cùng thời gian đăng (0h): Tin A (Score 10/10 → Final 30); Tin B (Score 6/10 → Final 18)'],
    testData: 'Danh sách tin cùng hạng',
    testSteps: '1. Xem danh sách tin VIP Vàng. 2. So sánh thứ tự hiển thị.',
    expectedResult: 'Tin A xếp trên Tin B.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-RANK-ORDER-004',
    title: '[Core Rule 2 – Time Decay] Cùng hạng VIP Bạc, tin mới đăng xếp TRÊN tin đăng lâu',
    module: 'Ranking',
    priority: 'high',
    tags: rankingTags,
    preconditions: ['Seed: 2 tin cùng gói VIP Bạc, cùng điểm chất lượng 10/10: Tin A (vừa đăng 1h) vs Tin B (đăng 48h)'],
    testData: 'Danh sách tin VIP Bạc',
    testSteps: '1. Kiểm tra vị trí Tin A/Tin B.',
    expectedResult: 'Tin A (mới hơn, Final Score cao hơn) xếp trên Tin B.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-RANK-ORDER-005',
    title: '[Decay Rate] Tốc độ giảm điểm VIP Kim Cương (0.01) chậm hơn hẳn Tin Thường (0.08)',
    module: 'Ranking',
    priority: 'high',
    tags: rankingTags,
    preconditions: ['Seed: 2 tin cùng đăng 48h trước, cùng điểm chất lượng 10/10: Tin A (Kim Cương) vs Tin B (Tin Thường)'],
    testData: 'Thời gian đã đăng: 48h',
    testSteps: '1. Gọi API/Request kiểm tra finalScore trả về từ Backend cho cả 2 tin (hoặc suy ra qua vị trí DOM nếu không có API).',
    expectedResult: 'Tỷ lệ giảm điểm của Tin B giảm mạnh hơn nhiều lần so với Tin A — thể hiện đúng cơ chế tốc độ giảm điểm khác nhau theo hạng gói (Mục 4–5).',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-RANK-QUAL-001',
    title: '[Quality Score Effect] Bổ sung đầy đủ giấy tờ pháp lý/mô tả giúp tăng Điểm chất lượng và đẩy vị trí hiển thị',
    module: 'Ranking',
    priority: 'medium',
    tags: rankingTags,
    preconditions: ['Tin A đang ở VIP Bạc, thiếu ảnh pháp lý (Score 6/10), đang xếp dưới Tin B (VIP Bạc, Score 8/10)'],
    testData: 'Bổ sung 2 ảnh sổ đỏ hợp lệ + mô tả chi tiết',
    testSteps: '1. Sửa tin A, bổ sung giấy tờ pháp lý + mô tả. 2. Nhấn "Cập nhật". 3. Reload danh sách tin cùng hạng.',
    expectedResult: 'Điểm chất lượng Tin A tăng 6→10; Điểm gốc/Điểm hiển thị tăng theo, đẩy Tin A lên trên Tin B.',
    automation: { status: 'NOT_AUTOMATED' as const },
  }
];
