import { TAGS } from '../../constants/tags';
import type { TestCaseDefinition } from '../../types/test-case.types';

const listingTags = Object.freeze([TAGS.regression, TAGS.listings]);

export const listingTestCases: readonly TestCaseDefinition[] = [
  {
    id: 'TC-LIST-CREATE-001',
    title: '[Happy Path] Tạo tin đăng "Mua bán" thành công đầy đủ thông tin',
    module: 'Listings',
    priority: 'critical',
    tags: listingTags,
    preconditions: ['User đã đăng nhập, đã có SĐT hợp lệ'],
    testData: 'Loại hình: Mua bán; Tiêu đề: "Bán căn hộ 2PN Vinhomes"; Giá: 3.5 tỷ; Pháp lý: "Sổ hồng riêng"; Diện tích, địa chỉ, ảnh hợp lệ',
    testSteps: '1. Chọn "Mua bán". 2. Nhập đầy đủ trường bắt buộc. 3. Upload 1–10 ảnh hợp lệ. 4. Nhập Họ tên/SĐT liên hệ hợp lệ. 5. Click "Đăng tin".',
    expectedResult: 'Hệ thống tính điểm chất lượng tin, lưu DB với trạng thái "Chờ duyệt"; hiển thị popup/toast thông báo thành công.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/create-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-CREATE-002',
    title: '[Happy Path] Tạo tin đăng "Cho thuê" thành công đầy đủ thông tin',
    module: 'Listings',
    priority: 'critical',
    tags: listingTags,
    preconditions: ['User đã đăng nhập, đã có SĐT hợp lệ'],
    testData: 'Loại hình: Cho thuê; Giá thuê: 7 triệu/tháng; Tiền cọc: 14 triệu; Thời gian thuê, kỳ thanh toán hợp lệ',
    testSteps: '1. Chọn "Cho thuê". 2. Nhập đầy đủ trường bắt buộc + Thời gian thuê/Kỳ thanh toán. 3. Upload ảnh hợp lệ. 4. Click "Đăng tin".',
    expectedResult: 'Tin lưu DB với trạng thái "Chờ duyệt"; trường Tiền cọc/Giá thuê ghi nhận chính xác.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/create-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-CREATE-003',
    title: '[UI Context Logic] Ẩn/hiện trường đặc thù khi chuyển đổi Mua bán ↔ Cho thuê',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Chuyển đổi qua lại 2 radio',
    testSteps: '1. Chọn "Cho thuê", quan sát form. 2. Chọn "Mua bán", quan sát form.',
    expectedResult: 'Cho thuê: hiện "Tiền cọc", nhãn đổi "Giá thuê". Mua bán: ẩn "Tiền cọc", hiện "Pháp lý", nhãn đổi "Giá bán".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-004',
    title: '[Required Validation] Chặn tạo tin khi thiếu Tiêu đề / thiếu Loại nhà đất',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Tiêu đề hoặc Loại nhà đất: để trống',
    testSteps: '1. Điền các trường khác hợp lệ, bỏ trống 1 trong 2 trường trên. 2. Blur/submit.',
    expectedResult: 'Hiển thị lỗi bắt buộc tương ứng, không gọi API.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-005',
    title: '[Boundary] Tự động cắt chuỗi khi paste Tiêu đề / Họ tên người liên hệ vượt giới hạn',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Tiêu đề: paste 140 ký tự (giới hạn 120); Họ tên liên hệ: paste 65 ký tự (giới hạn 50)',
    testSteps: '1. Paste chuỗi vượt giới hạn vào từng field tương ứng.',
    expectedResult: 'Tiêu đề: tự động cắt còn 120 ký tự. Họ tên liên hệ: tự động cắt còn 50 ký tự, loại bỏ khoảng trắng đầu/cuối.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-006',
    title: '[Business Rule] Mô tả < 20 ký tự / Diện tích ≤ 0 / Giá ≤ 0 bị chặn',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Mô tả: "Nhà đẹp" (<20 ký tự); Diện tích: "0"; Giá: "0"',
    testSteps: '1. Nhập từng giá trị không hợp lệ vào field tương ứng. 2. Blur khỏi field.',
    expectedResult: 'Hiển thị đúng lỗi cho từng field: Mô tả chưa đạt tối thiểu 20 ký tự; "Diện tích không hợp lệ hoặc vượt giới hạn"; "Giá phải lớn hơn 0".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-007',
    title: '[Business Logic] Input Giá bị disable và xóa giá trị khi chọn "Thương lượng"',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Đã nhập số vào Giá, sau đó chọn "Thương lượng"',
    testSteps: '1. Nhập số vào trường Giá. 2. Chọn "Thương lượng".',
    expectedResult: 'Input Giá chuyển disabled và giá trị vừa nhập bị xóa về rỗng.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-008',
    title: '[Media Validation] Chặn upload ảnh BĐS vượt 10 ảnh / sai định dạng / vượt 30MB',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng. File test sẵn sai định dạng/quá dung lượng.'],
    testData: '10 ảnh hợp lệ + thử ảnh thứ 11; 1 file sai định dạng; 1 file >30MB',
    testSteps: '1. Upload đủ 10 ảnh, thử thêm ảnh 11. 2. Upload file sai định dạng. 3. Upload file >30MB.',
    expectedResult: 'Case 1: chặn không cho thêm. Case 2 & 3: hiển thị lỗi upload tương ứng, không thêm vào preview.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-009',
    title: '[Media Validation] Chặn upload Giấy tờ pháp lý vượt 5 ảnh hoặc vượt 10MB',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: '6 ảnh hợp lệ; hoặc 1 ảnh 15MB',
    testSteps: '1. Kéo/thả 6 ảnh vào mục Giấy tờ pháp lý. 2. Thử upload 1 ảnh 15MB.',
    expectedResult: 'Hệ thống chặn file thừa/vượt dung lượng ngay tại UI, hiển thị lỗi "Cho phép tối đa 5 ảnh, mỗi file ≤10MB".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-010',
    title: '[Input Validation] Chặn ký tự đặc biệt/số âm/số thập phân ở Số phòng ngủ, Số phòng tắm',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'Nhập lần lượt: `-5`, `2.5`, `abc`',
    testSteps: '1. Nhập từng giá trị vào ô Số phòng ngủ/tắm. 2. Blur khỏi field.',
    expectedResult: 'Hệ thống xóa ký tự không hợp lệ hoặc báo lỗi "Chỉ cho phép nhập số tự nhiên".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-011',
    title: '[Format Validation] SĐT liên hệ sai định dạng bị từ chối',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng'],
    testData: 'SĐT: "12345" (sai đầu số, thiếu số)',
    testSteps: '1. Nhập SĐT sai định dạng. 2. Blur khỏi field.',
    expectedResult: 'Hiển thị lỗi định dạng số điện thoại không hợp lệ.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-012',
    title: '[Business Rule] Chặn tạo tin khi tài khoản chưa cập nhật số điện thoại',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Tài khoản (VD: mới tạo qua Google OAuth) chưa có SĐT trong hồ sơ'],
    testData: 'Dữ liệu đăng tin hợp lệ',
    testSteps: '1. Truy cập "Đăng tin" hoặc cố submit bằng tài khoản chưa có SĐT.',
    expectedResult: 'Hệ thống chặn hành động đăng tin, yêu cầu bổ sung SĐT trước, dừng luồng.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-CREATE-013',
    title: '[Required Validation] Chặn đăng tin "Cho thuê" khi bỏ trống Tiền cọc',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đang ở form Tạo tin đăng, đã chọn "Cho thuê"'],
    testData: 'Tiền cọc: để trống, các trường khác hợp lệ',
    testSteps: '1. Chọn "Cho thuê". 2. Điền đủ các trường khác, bỏ trống "Tiền cọc". 3. Click "Đăng tin".',
    expectedResult: 'Hệ thống chặn gọi API, hiển thị lỗi "Tiền cọc là trường bắt buộc đối với loại hình cho thuê".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-VIEW-001',
    title: 'Xem danh sách tin đăng của tôi + tìm kiếm trong danh sách',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đã đăng nhập, có ≥1 tin đăng'],
    testData: 'Từ khóa khớp 1 tin của User A',
    testSteps: '1. Truy cập "Danh sách tin đăng". 2. Nhập từ khóa tìm kiếm trong danh sách.',
    expectedResult: 'Hiển thị đúng danh sách tin của User A; kết quả tìm kiếm lọc đúng theo từ khóa.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/view-own-listings.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-VIEW-002',
    title: 'Hiển thị rỗng khi không có tin đăng / không có kết quả tìm kiếm',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['Tài khoản chưa có tin đăng; hoặc từ khóa không khớp'],
    testData: 'Tài khoản mới; từ khóa không tồn tại',
    testSteps: '1. Truy cập danh sách khi chưa có tin. 2. Tìm kiếm với từ khóa không khớp.',
    expectedResult: 'Cả 2 trường hợp hiển thị empty state phù hợp.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/view-own-listings.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-DETAIL-001',
    title: 'Xem chi tiết tin đăng đã duyệt thành công',
    module: 'Listings',
    priority: 'critical',
    tags: listingTags,
    preconditions: ['Tồn tại tin đăng "Đã duyệt"'],
    testData: 'Tin đăng đã duyệt',
    testSteps: '1. Click vào tin đăng đã duyệt.',
    expectedResult: 'Hiển thị đầy đủ thông tin, hình ảnh/video, mô tả, liên hệ, tiện ích, tin liên quan; view count tăng.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/listing-detail.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-DETAIL-002',
    title: 'Không tồn tại / chưa duyệt → không hiển thị nội dung',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['PostID không tồn tại; hoặc tin ở trạng thái "Chờ duyệt"'],
    testData: 'PostID invalid; tin chưa duyệt',
    testSteps: '1. Truy cập chi tiết với PostID không tồn tại. 2. Truy cập trực tiếp chi tiết tin chưa duyệt.',
    expectedResult: 'Case 1: "Tin không tồn tại". Case 2: không hiển thị nội dung.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/listing-detail.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-EDIT-001',
    title: '[State Transition] Chỉnh sửa tin thành công, tự động chuyển về "Chờ duyệt"',
    module: 'Listings',
    priority: 'critical',
    tags: listingTags,
    preconditions: ['Tin đăng của User đang "Đang đăng"'],
    testData: 'Sửa nội dung mô tả',
    testSteps: '1. Chọn "Sửa" trên tin đăng. 2. Thay đổi nội dung. 3. Nhấn "Cập nhật".',
    expectedResult: 'Dữ liệu mới lưu vào DB; trạng thái chuyển từ "Đang đăng" về "Chờ duyệt".',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/component/pages/ListingFormComponent.spec.ts' },
  },
  {
    id: 'TC-LIST-EDIT-002',
    title: '[Permission Security] Chặn sửa tin đăng của người dùng khác',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User B đã đăng nhập; PostID thuộc sở hữu User A'],
    testData: 'URL: /listing/edit/{PostID_of_A}',
    testSteps: '1. Tại tài khoản User B, truy cập trực tiếp URL sửa tin của User A.',
    expectedResult: 'Hệ thống từ chối, hiển thị "Bạn không có quyền chỉnh sửa bài viết này" hoặc redirect về trang quản lý cá nhân.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/edit-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-REMOVE-001',
    title: '[State Transition] Gỡ tin đăng thành công khi đang "Đang đăng"',
    module: 'Listings',
    priority: 'critical',
    tags: listingTags,
    preconditions: ['Tin đăng của User đang "Đang đăng"'],
    testData: 'Tin đăng "Đang đăng"',
    testSteps: '1. Nhấn "Gỡ tin". 2. Xác nhận tại popup.',
    expectedResult: 'Trạng thái chuyển "Đã gỡ"; tin biến mất khỏi trang công khai.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/withdraw-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-REMOVE-002',
    title: '[Business Rule] Chặn gỡ tin khi trạng thái không phải "Đang đăng"',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Tin đăng ở trạng thái "Chờ duyệt"/"Bị từ chối"'],
    testData: 'Tin đăng "Chờ duyệt"',
    testSteps: '1. Cố gắng gỡ tin không ở trạng thái "Đang đăng" (qua UI hoặc API).',
    expectedResult: 'Hệ thống từ chối, giữ nguyên trạng thái ban đầu.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/withdraw-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-FAVORITE-001',
    title: '[Happy Path / CRUD] Thêm và bỏ tin đăng khỏi Yêu thích',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đã đăng nhập, tin chưa yêu thích'],
    testData: 'Tin đăng bất kỳ',
    testSteps: '1. Click icon Trái tim → thêm yêu thích, kiểm tra tại trang "Tin đăng yêu thích". 2. Click lại icon Trái tim → bỏ yêu thích.',
    expectedResult: 'Bước 1: icon active, tin xuất hiện trong danh sách yêu thích. Bước 2: tin biến mất khỏi danh sách yêu thích.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/favorite-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-FAVORITE-002',
    title: 'Chuyển hướng đăng nhập khi thêm yêu thích lúc chưa đăng nhập',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['Người dùng chưa đăng nhập'],
    testData: '-',
    testSteps: '1. Nhấn icon Trái tim khi chưa đăng nhập.',
    expectedResult: 'Chuyển tới màn hình đăng nhập.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/favorite-listing.mutating.spec.ts' },
  },
  {
    id: 'TC-LIST-VERIFY-001',
    title: 'Gửi hồ sơ xác thực tin đăng thành công',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Chủ tin, tin thuộc nhu cầu Mua bán, chưa có hồ sơ "Chờ duyệt"'],
    testData: 'CCCD 2 mặt + giấy tờ pháp lý hợp lệ',
    testSteps: '1. Upload CCCD mặt trước/sau, giấy tờ pháp lý. 2. Nhấn "Đăng lại tin".',
    expectedResult: 'Hồ sơ lưu, trạng thái xác thực → "Chờ duyệt".',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-VERIFY-002',
    title: 'Chặn gửi hồ sơ khi thiếu ảnh bắt buộc hoặc sai định dạng/dung lượng',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Đang ở form xác thực'],
    testData: 'Thiếu 1 trong 3 ảnh bắt buộc; hoặc file sai định dạng/>30MB',
    testSteps: '1. Bỏ qua 1 ảnh bắt buộc hoặc upload sai định dạng/quá dung lượng. 2. Nhấn "Đăng lại tin".',
    expectedResult: 'Hiển thị lỗi tương ứng, không lưu hồ sơ.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-REPORT-001',
    title: '[Happy Path] Gửi báo cáo vi phạm tin đăng thành công',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['User đã đăng nhập, đang xem tin của người khác'],
    testData: 'Lý do: "Giá không đúng thực tế, tin ảo"',
    testSteps: '1. Nhấn "Báo cáo tin đăng". 2. Chọn lý do, nhập mô tả chi tiết. 3. Nhấn "Gửi phản ánh".',
    expectedResult: 'Báo cáo lưu vào DB thành công; popup tự đóng; hiển thị toast thành công; tin bị gắn cờ cảnh báo.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-REPORT-002',
    title: 'Chặn gửi báo cáo khi bỏ trống lý do xác nhận',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['Đang ở popup xác nhận báo cáo'],
    testData: 'Lý do: ""',
    testSteps: '1. Để trống ô lý do. 2. Nhấn xác nhận.',
    expectedResult: 'Hệ thống chặn gửi (nguồn: kết quả kiểm thử thực tế "chặn gửi chuỗi rỗng").',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-FILTER-001',
    title: 'Lọc theo Người đăng (Chủ nhà/Môi giới) + khoảng giá tùy chỉnh',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Danh sách có dữ liệu đa dạng'],
    testData: 'Người đăng: Chủ nhà/Môi giới; Giá Từ<Đến',
    testSteps: '1. Chọn Người đăng. 2. Nhập khoảng giá hợp lệ. 3. Áp dụng bộ lọc.',
    expectedResult: 'Danh sách lọc đúng theo cả 2 điều kiện.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/filter-listing.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-FILTER-002',
    title: 'Lọc thất bại khi khoảng giá/diện tích không hợp lệ (Từ > Đến)',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Danh sách có dữ liệu'],
    testData: 'Giá/Diện tích Từ > Đến',
    testSteps: '1. Nhập Từ > Đến cho giá hoặc diện tích. 2. Áp dụng.',
    expectedResult: 'Hiển thị lỗi khoảng giá trị không hợp lệ tương ứng.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/filter-listing.read-only.spec.ts' },
  },
  {
    id: 'TC-LIST-FILTER-003',
    title: 'Đặt lại bộ lọc về mặc định',
    module: 'Listings',
    priority: 'medium',
    tags: listingTags,
    preconditions: ['Đã áp dụng ≥1 điều kiện lọc'],
    testData: '-',
    testSteps: '1. Nhấn "Đặt lại bộ lọc".',
    expectedResult: 'Toàn bộ điều kiện về mặc định, danh sách trở về ban đầu.',
    automation: { status: 'NOT_AUTOMATED' as const },
  },
  {
    id: 'TC-LIST-SEARCH-001',
    title: 'Tìm kiếm tin đăng theo từ khóa (có kết quả / không có kết quả)',
    module: 'Listings',
    priority: 'high',
    tags: listingTags,
    preconditions: ['Hệ thống có dữ liệu tin đăng'],
    testData: 'Từ khóa khớp dữ liệu; từ khóa không khớp',
    testSteps: '1. Tìm với từ khóa khớp → kiểm tra kết quả. 2. Tìm với từ khóa không khớp → kiểm tra empty state.',
    expectedResult: 'Case 1: trả kết quả đúng, loại tin không đủ điều kiện, sắp xếp mặc định. Case 2: thông báo không tìm thấy.',
    automation: { status: 'AUTOMATED' as const, scriptPath: 'tests/listings/search-listing.read-only.spec.ts' },
  }
];

export const getListingTestCase = (id: string): TestCaseDefinition => {
  const testCase = listingTestCases.find((candidate) => candidate.id === id);
  if (testCase === undefined) throw new Error(`Unknown listing test case: ${id}`);
  return testCase;
};

export const listingCaseTitle = (id: string): string => {
  const testCase = getListingTestCase(id);
  return `${testCase.id} ${testCase.title} ${testCase.tags.join(' ')}`;
};
